---
title: "Dispute Resolution: Exploratory Analysis"
output: html_notebook
---

```{r}
library(tidyverse, verbose = T)
library(stringr, verbose = T)
```

```{r read files}
fnames <- c(
  "https://www2.ed.gov/programs/osepidea/618-data/state-level-data-files/part-b-data/dispute-resolution/bdispres2014-15.csv",
  "https://www2.ed.gov/programs/osepidea/618-data/state-level-data-files/part-b-data/dispute-resolution/bdispres2013-14.csv", 
  "https://www2.ed.gov/programs/osepidea/618-data/state-level-data-files/part-b-data/dispute-resolution/bdispres2012-13.csv"#,
  # Having trouble reading in the first row with these.
  #"https://www2.ed.gov/programs/osepidea/618-data/state-level-data-files/part-b-data/dispute-resolution/bdispres2011-12.csv",
  #"https://www2.ed.gov/programs/osepidea/618-data/state-level-data-files/part-b-data/dispute-resolution/bdispres2010-11.csv"
)

# Read files
allfiles <- lapply(fnames, function(x) {read_csv(
  x, 
  skip = 4, 
  col_types = cols(.default = "c"), 
  n_max = 61
  )})

# Combine and convert to tidy format
comb <- bind_rows(allfiles) %>%
  gather(category, total, -c(Year, State)) %>%
  mutate(total = as.numeric(total))
```

Clean up and simplify the column names. 

```{r}
cnames <- names(comb) %>% 
  str_replace_all("\\(", "") %>% 
  str_replace_all("\\)", "") 

for (i in 3:length(cnames)) {
 str_sub(
  cnames[i],
  str_locate(cnames[i], regex("[0-9]"))[1, 1], 
  str_length(cnames[i])
  ) <- ""
}

cnames <- str_trim(cnames, "right")

names(comb) <- cnames
```


```{r by state in 14-15}
# Total due process complains in 14-15 by state
by_state_14 <- comb %>%
  filter(
    Year     == "2014-2015", 
    category == "Due Process Complaints (DPC) Total (3)"
    ) %>%
  arrange(desc(total))

ggplot(data = by_state_14, aes(reorder(x = State, total), y = total)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(
    title = "Total Due Process Complaints", 
    subtitle = "2014-2015", 
    x = "State"
    )
```

```{r by state in 13-14}
# Total due process complains in 13-14 by state
by_state_13 <- comb %>%
  filter(
    Year     == "2013-2014", 
    category == "Due Process Complaints (DPC) Total (3)"
    ) %>%
  arrange(desc(total))
```

```{r by state in 12-13}
# Total due process complains in 12-13 by state
by_state_12 <- comb %>%
  filter(
    Year     == "2012-2013", 
    category == "Due Process Complaints (DPC) Total (3)"
    ) %>%
  arrange(desc(total))
```

```{r}
# What is the median number of due process complaints?
p <- ggplot(data = filter(
  comb, 
  category == "Due Process Complaints (DPC) Total (3)"), 
  aes(x = Year, y = total)) +
  geom_boxplot() + 
  labs(title = "Median Total Due Process Complaints")

# Zoom in on totals of less than 500
p + coord_cartesian(ylim = c(0, 500))
```

```{r}
# TODO Need to find a better way to explore year to year
#ggplot(data = filter(
#  comb,
#  category == "Due Process Complaints (DPC) Total (3)"),
#  aes(x = State, y = total)
#  ) +
#  geom_bar(stat = "identity") +
#  coord_flip() +
#  facet_wrap(~ Year)
```

```{r mediation agreements}
# What is the relationship between mediations held and mediation agreements?
# This looks just at mediations relating to due process hearings.
med <- comb %>%
  filter(
    category == "Mediations Held Related to Due Process Complaints(2.1a)" | 
    category == "Mediation Agreements Related to Due Process Complaints (2.1ai)"
  ) %>%
  spread(key = category, value = total)

med_plot <- ggplot(data = med) +
  geom_point(aes(
    x = `Mediations Held Related to Due Process Complaints(2.1a)`, 
    y = `Mediation Agreements Related to Due Process Complaints (2.1ai)`
  ), 
    position = "jitter",
    alpha = .50) + 
  geom_smooth(aes(
  x = `Mediations Held Related to Due Process Complaints(2.1a)`, 
  y = `Mediation Agreements Related to Due Process Complaints (2.1ai)`
  )) +
  facet_wrap(~ Year) +
  labs(
    title    = "Mediations Held vs. Mediation Agreements",
    subtitle = "Dataset includes only mediations related to due process complaints.",
    x        = "Mediations held relating to due process", 
    y        = "Agreements reached"
    )

# Zoom in on x < 1000 and 6 < 500
med_plot + coord_cartesian(xlim = c(0, 1000), ylim = c(0, 500))
```